source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'CustomUIWidget_Example' do
  pod 'CustomUIWidget', :path => '../'
  pod 'Masonry'
  pod 'YYCategories'
  target 'CustomUIWidget_Tests' do
    inherit! :search_paths

    
  end
end
