#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target 'CustomUIWidget_Example' do
  pod 'CustomUIWidget', :path => '../'
  pod 'Masonry'
  pod 'YYCategories'
  pod 'YYText'
  pod 'YYModel'
  pod 'YYWebImage'
  pod 'libextobjc'
  pod 'Aspects'
end
